[project]
name = "01-hitl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain>=1.0.8",
    "langchain-deepseek>=1.0.1",
    "langgraph>=1.0.3",
    "langgraph-checkpoint-mongodb>=0.3.0",
    "loguru>=0.7.3",
    "python-dotenv>=1.2.1",
]
